INSERT INTO PROFESSOR (NOME, SOBRE_NOME) VALUES ('Fabio', 'Kuhnen');
INSERT INTO PROFESSOR (NOME, SOBRE_NOME) VALUES ('Priscila', 'Silva');
INSERT INTO PROFESSOR (NOME, SOBRE_NOME) VALUES ('Camila', 'Souza');

INSERT INTO ALUNO (RA, NOME, SOBRE_NOME) VALUES ('2316', 'João', 'Kuhnen');
INSERT INTO ALUNO (RA, NOME, SOBRE_NOME) VALUES ('1640', 'Bianca', 'Silva');
INSERT INTO ALUNO (RA, NOME, SOBRE_NOME) VALUES ('5568', 'Jardel', 'Kuhnen');
INSERT INTO ALUNO (RA, NOME, SOBRE_NOME) VALUES ('9958', 'Maria', 'Silva');

INSERT INTO TURMA (NOME) VALUES ('Terceiro A');
INSERT INTO TURMA (NOME) VALUES ('Terceiro B');
INSERT INTO TURMA (NOME) VALUES ('Terceiro C');

INSERT INTO MATERIA (NOME, PROFESSOR_ID) VALUES ('Matemática', 1);
INSERT INTO MATERIA (NOME, PROFESSOR_ID) VALUES ('Português', 2);


